version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      cargo-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
